title: "Nguyễn Lê Trọng Tín"
tagline: "Cyber Security Student | SOC | HTB Learner"
description: "Personal cybersecurity notes, HTB writeups, SOC labs and DFIR learning."

url: "https://USERNAME.github.io"

avatar: "/assets/img/avatar.png"

github:
  username: USERNAME

twitter:
  username: your_twitter
