title: "Nguyễn Lê Trọng Tín"
tagline: "Cyber Security Student | SOC | HTB Learner"
description: "Personal cybersecurity notes, HTB writeups, SOC labs and DFIR learning."

url: "https://tindaptrai.github.io"
baseurl: "/trongtin.github.io"

github:
  username: Tindaptrai

social:
  name: "Nguyễn Lê Trọng Tín"
  links:
    - "https://github.com/Tindaptrai"

avatar: "/assets/img/avatar.png"

timezone: Asia/Ho_Chi_Minh
lang: vi-VN

theme: jekyll-theme-chirpy

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate-v2
